// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sky.ERP.Infrastructure.Data;

namespace Sky.ERP.Infrastructure.Migrations
{
    [DbContext(typeof(SkyERPDBContext))]
    [Migration("20210901050253_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sky.ERP.Domain.Entities.Common.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branchid");

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("cityid");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createby");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isactive");

                    b.Property<bool?>("IsBilling")
                        .HasColumnType("bit")
                        .HasColumnName("isbilling");

                    b.Property<bool?>("IsPhysical")
                        .HasColumnType("bit")
                        .HasColumnName("isphysical");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("isremoved");

                    b.Property<bool?>("IsShipping")
                        .HasColumnType("bit")
                        .HasColumnName("isshipping");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("line2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("postalcode");

                    b.Property<long?>("StateId")
                        .HasColumnType("bigint")
                        .HasColumnName("stateid");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("street");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Sky.ERP.Domain.Entities.Common.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AccCashId")
                        .HasColumnType("bigint")
                        .HasColumnName("acccashid");

                    b.Property<long?>("AccDiscountAcquiredId")
                        .HasColumnType("bigint")
                        .HasColumnName("accdiscountacquiredid");

                    b.Property<long?>("AccInventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("accinventoryid");

                    b.Property<long?>("AccPurchasesId")
                        .HasColumnType("bigint")
                        .HasColumnName("accpurchasesid");

                    b.Property<long?>("AccPurchasesReturnsId")
                        .HasColumnType("bigint")
                        .HasColumnName("accpurchasesreturnsid");

                    b.Property<long?>("AccSalesCostId")
                        .HasColumnType("bigint")
                        .HasColumnName("accsalescostid");

                    b.Property<long?>("AccSalesId")
                        .HasColumnType("bigint")
                        .HasColumnName("accsalesid");

                    b.Property<long?>("AccSalesTaxonPurchasesId")
                        .HasColumnType("bigint")
                        .HasColumnName("accsalestaxonpurchasesid");

                    b.Property<long?>("AccSuppliersId")
                        .HasColumnType("bigint")
                        .HasColumnName("accsuppliersid");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("addressid");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branchid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("CommercialNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("commercialno");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("contactid");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createby");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<long?>("DefaultCostCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("defaultcostcenterid");

                    b.Property<long?>("DefaultCurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("defaultcurrencyid");

                    b.Property<long?>("DefaultInventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("defaultinventoryid");

                    b.Property<int?>("InventoryAccountingTypes")
                        .HasColumnType("int")
                        .HasColumnName("inventoryaccountingtypes");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("isremoved");

                    b.Property<string>("LogoURL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logourl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<bool?>("ShowLogo")
                        .HasColumnType("bit")
                        .HasColumnName("showlogo");

                    b.Property<string>("SiteURL")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("siteurl");

                    b.Property<int?>("SystemType")
                        .HasColumnType("int")
                        .HasColumnName("systemtype");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BranchId = 0L,
                            Code = "001",
                            CreateBy = 0L,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "Main Branch"
                        });
                });

            modelBuilder.Entity("Sky.ERP.Domain.Entities.Common.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branchid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createby");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("isremoved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<float?>("Rate")
                        .HasColumnType("real")
                        .HasColumnName("rate");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symbol");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Sky.ERP.Domain.Entities.GL.GLChart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNature")
                        .HasColumnType("int")
                        .HasColumnName("accountnature");

                    b.Property<int>("AccountOrder")
                        .HasColumnType("int")
                        .HasColumnName("accountorder");

                    b.Property<int>("AccountType")
                        .HasColumnType("int")
                        .HasColumnName("accounttype");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branchid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createby");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("currencyid");

                    b.Property<long>("FinalAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("finalaccountid");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("isremoved");

                    b.Property<long>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("bigint")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parentid");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_glchart");

                    b.ToTable("GLChart");
                });

            modelBuilder.Entity("Sky.ERP.Domain.Entities.HR.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branchid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createby");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("isremoved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Sky.ERP.Domain.Entities.HR.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("addressid");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branchid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint")
                        .HasColumnName("contactid");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createby");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<DateTime?>("DateofBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateofbirth");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("departmentid");

                    b.Property<string>("FatherName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("fathername");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("firstname");

                    b.Property<int?>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imageurl");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("isremoved");

                    b.Property<long?>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("jobid");

                    b.Property<string>("LastName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("lastname");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("machinecode");

                    b.Property<long?>("ManagementId")
                        .HasColumnType("bigint")
                        .HasColumnName("managementid");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("managerid");

                    b.Property<int?>("MaterialState")
                        .HasColumnType("int")
                        .HasColumnName("materialstate");

                    b.Property<int?>("MilitaryService")
                        .HasColumnType("int")
                        .HasColumnName("militaryservice");

                    b.Property<string>("MotherName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("mothername");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("placeofbirth");

                    b.Property<int?>("ReligionID")
                        .HasColumnType("int")
                        .HasColumnName("religionid");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.Property<long?>("WorkStatusID")
                        .HasColumnType("bigint")
                        .HasColumnName("workstatusid");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Sky.ERP.Domain.Entities.Inventory.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttentionExpirDate")
                        .HasColumnType("int")
                        .HasColumnName("attentionexpirdate");

                    b.Property<int>("Barcode")
                        .HasMaxLength(150)
                        .HasColumnType("int")
                        .HasColumnName("barcode");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branchid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryid");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<int>("ColorArgb")
                        .HasColumnType("int")
                        .HasColumnName("colorargb");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createby");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<int>("DefaultSupplier")
                        .HasColumnType("int")
                        .HasColumnName("defaultsupplier");

                    b.Property<int>("DemandLimit")
                        .HasColumnType("int")
                        .HasColumnName("demandlimit");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<bool?>("HasSeries")
                        .HasColumnType("bit")
                        .HasColumnName("hasseries");

                    b.Property<int>("HighestRate")
                        .HasColumnType("int")
                        .HasColumnName("highestrate");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imageurl");

                    b.Property<int>("IntervalRecession")
                        .HasColumnType("int")
                        .HasColumnName("intervalrecession");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isactive");

                    b.Property<bool?>("IsHasColors")
                        .HasColumnType("bit")
                        .HasColumnName("ishascolors");

                    b.Property<bool?>("IsHasExpirDate")
                        .HasColumnType("bit")
                        .HasColumnName("ishasexpirdate");

                    b.Property<bool?>("IsHasSizes")
                        .HasColumnType("bit")
                        .HasColumnName("ishassizes");

                    b.Property<bool?>("IsHasWarranty")
                        .HasColumnType("bit")
                        .HasColumnName("ishaswarranty");

                    b.Property<bool>("IsKitchenPrint")
                        .HasColumnType("bit")
                        .HasColumnName("iskitchenprint");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("isremoved");

                    b.Property<int>("KitchenId")
                        .HasColumnType("int")
                        .HasColumnName("kitchenid");

                    b.Property<int>("MonthlySalesTarget")
                        .HasColumnType("int")
                        .HasColumnName("monthlysalestarget");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.Property<int>("ProductType")
                        .HasColumnType("int")
                        .HasColumnName("producttype");

                    b.Property<int>("SortId")
                        .HasColumnType("int")
                        .HasColumnName("sortid");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Sky.ERP.Domain.Entities.Inventory.ProductMaterial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branchid");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createby");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("isremoved");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("productid");

                    b.Property<long>("ProductMaterialId")
                        .HasColumnType("bigint")
                        .HasColumnName("productmaterialid");

                    b.Property<float>("Quantity")
                        .HasColumnType("real")
                        .HasColumnName("quantity");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_productmaterials");

                    b.ToTable("ProductMaterials");
                });

            modelBuilder.Entity("Sky.ERP.Domain.Entities.Inventory.ProductSize", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branchid");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createby");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("isremoved");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("productid");

                    b.Property<long>("SizeId")
                        .HasColumnType("bigint")
                        .HasColumnName("sizeid");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_productsizes");

                    b.ToTable("ProductSizes");
                });

            modelBuilder.Entity("Sky.ERP.Domain.Entities.Sales.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("addressid");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branchid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint")
                        .HasColumnName("contactid");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createby");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("isremoved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
